# Generated by Django 4.2.6 on 2023-10-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Poll',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='question_text',
            new_name='question',
        ),
    ]
